name: Build PR preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-preview:
    name: Build preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v3

      - name: Build 🏗️
        uses: ./.github/actions/build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Upload build files 📤
        uses: sliit-foss/actions/preview-deployments/postbuild@main
